goal_description: please help me to map the reads to mouse genome,
data_list: 
  ./data/SRR1374921.fastq.gz: single-end mouse rna-seq reads, replicate 1 in LoGlu group
  ./data/SRR1374922.fastq.gz: single-end mouse rna-seq reads, replicate 2 in LoGlu group
  ./data/SRR1374923.fastq.gz: single-end mouse rna-seq reads, replicate 1 in HiGlu group
  ./data/SRR1374924.fastq.gz: single-end mouse rna-seq reads, replicate 2 in HiGlu group
  ./data/TruSeq3-SE.fa: trimming adapter
  ./data/mm39.fa: mouse mm39 genome fasta
  ./data/mm39.ncbiRefSeq.gtf: mouse mm39 genome annotation
output_dir: ./output
working_dir: /Users/liguowei/ubuntu/smolagents/examples/genome